language: php

php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"

install:
  - composer config -g github-oauth.github.com "$GITHUB_API_KEY"
  - ./tools/strip-reference-deps.sh
  - composer require --no-update symfony/http-foundation $SYMFONY_VERSION; composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/php-cs-fixer fix -v --dry-run

# jobs:
#   include:
#     - stage: before_install
#       script: ./tools/strip-reference-deps.sh

env:
  - SYMFONY_VERSION: ~2
  - SYMFONY_VERSION: ~3
  - SYMFONY_VERSION: ~4

matrix:
  exclude:
  - php: "7.0"
    env: SYMFONY_VERSION=~4
  - php: "7.1"
    env: SYMFONY_VERSION=~4
  - php: "7.2"
    env: SYMFONY_VERSION=~4
  - php: "7.3"
    env: SYMFONY_VERSION=~4
  - php: "7.4"
    env: SYMFONY_VERSION=~4

cache:
  directories:
    - $HOME/.composer/cache/files

branches:
  except:
  - doc
